AUDIT_ACTION_USER_BANNED = "UserBanned"
AUDIT_ACTION_USER_UNBANNED = "UserUnbanned"
AUDIT_ACTION_USER_UPDATE_OWN_PROFILE_IMAGE = "UserUpdateOwnProfileImage"
AUDIT_ACTION_USER_UPDATE_OTHERS_PROFILE_IMAGE = "UserUpdateOthersProfileImage"
AUDIT_ACTION_USER_UPDATE_OWN_PROFILE_NAME = "UserUpdateOwnProfileName"
AUDIT_ACTION_USER_UPDATE_OTHERS_PROFILE_NAME = "UserUpdateOthersProfileName"

AUDIT_USER_MODEL_ACTIONS = [
    AUDIT_ACTION_USER_BANNED,
    AUDIT_ACTION_USER_UNBANNED,
    AUDIT_ACTION_USER_UPDATE_OWN_PROFILE_NAME,
    AUDIT_ACTION_USER_UPDATE_OTHERS_PROFILE_NAME,
    AUDIT_ACTION_USER_UPDATE_OWN_PROFILE_IMAGE,
    AUDIT_ACTION_USER_UPDATE_OTHERS_PROFILE_IMAGE
]

AUDIT_ACTION_CREATE_CATEGORY = "CreateCategory"
AUDIT_ACTION_RENAME_CATEGORY = "RenameCategory"
AUDIT_ACTION_DELETE_CATEGORY = "DeleteCategory"

AUDIT_CATEGORY_MODEL_ACTIONS = [
    AUDIT_ACTION_CREATE_CATEGORY,
    AUDIT_ACTION_RENAME_CATEGORY,
    AUDIT_ACTION_DELETE_CATEGORY
]

AUDIT_ACTION_CREATE_THREAD = "CreateThread"
AUDIT_ACTION_RENAME_OWN_THREAD = "RenameOwnThread"
AUDIT_ACTION_RENAME_OTHERS_THREAD = "RenameOthersThread"
AUDIT_ACTION_DELETE_THREAD = "DeleteThread"

AUDIT_THREAD_MODEL_ACTIONS = [
    AUDIT_ACTION_CREATE_THREAD,
    AUDIT_ACTION_RENAME_OWN_THREAD,
    AUDIT_ACTION_RENAME_OTHERS_THREAD,
    AUDIT_ACTION_DELETE_THREAD
]

AUDIT_ACTION_CREATE_POST = "CreatePost"
AUDIT_ACTION_UPDATE_OWN_POST = "UpdateOwnPost"
AUDIT_ACTION_UPDATE_OTHERS_POST = "UpdateOthersPost"
AUDIT_ACTION_DELETE_POST = "DeletePost"

AUDIT_POST_MODEL_ACTIONS = [
    AUDIT_ACTION_CREATE_POST,
    AUDIT_ACTION_UPDATE_OWN_POST,
    AUDIT_ACTION_UPDATE_OTHERS_POST,
    AUDIT_ACTION_DELETE_POST
]

AUDIT_ACTION_USER_LIKE_POST = "LikePost"

AUDIT_USER_LIKE_POST_ACTIONS = [
    AUDIT_ACTION_USER_LIKE_POST
]

AUDIT_ACTION_ADMIN_EDIT_ROLE = "AdminEditRole"

AUDIT_ADMIN_EDIT_ROLE = [
    AUDIT_ACTION_ADMIN_EDIT_ROLE
]

AUDIT_ACTION_IDS = {}

ROLE_USER = "User"
ROLE_USER_LEVEL = 1000
ROLE_MODERATOR = "Moderator"
ROLE_MODERATOR_LEVEL = 100
ROLE_ADMIN = "Admin"
ROLE_ADMIN_LEVEL = 0

ROLES = {
    ROLE_ADMIN: ROLE_ADMIN_LEVEL,
    ROLE_MODERATOR: ROLE_MODERATOR_LEVEL,
    ROLE_USER: ROLE_USER_LEVEL
    
}

ROLE_IDS = {}
