version: "3.9"
services:
  chrome:
    image: selenium/node-chrome:4.0.0-20211025
    depends_on:
      - selenium-hub
    environment:
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_NODE_MAX_SESSIONS=10
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_GRID_URL=http://selenium-hub:4444
    ports:
      - "6900:4444"
    networks:
      - selenium_network

  selenium-hub:
    image: selenium/hub:4.0.0-20211025
    expose:
      - 4442
      - 4443
      - 4444
    networks:
      - selenium_network

networks:
  selenium_network:
    external: true